apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parking-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: parking-service
        version: v2
    spec:
      containers:
      - name: parking-service
        image: DOCKER_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
      imagePullSecrets:
      - name: ecr-secret
